In [6]:
import random
import numpy as np

"Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення."
vector = np.arange(1, 11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
"Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення."
matrix = np.zeros((3, 3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
"Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення."
matrix = np.random.randint(11, size=(5, 5))
print(matrix)

[[10  0  5  7  5]
 [ 7  5  9  7  6]
 [ 4  8  3  4  1]
 [ 4  6  9 10  6]
 [ 5  3  1  6 10]]


In [10]:
"Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення."
matrix = np.random.randint(2, size=(4, 4))
print(matrix)

[[0 0 0 0]
 [1 1 1 0]
 [1 1 1 1]
 [0 1 1 1]]


In [20]:
"Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення."
a = np.array([np.random.randint(1, 11) for i in range(5)])
b = np.array([np.random.randint(1, 11) for i in range(5)])

print(a + b)
print(a - b)
print(a * b)

[ 6  5 11 13 11]
[-4  1  7 -7  7]
[ 5  6 18 30 18]


In [29]:
"Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток."
a = np.array([np.random.randint(1, 11) for i in range(7)])
b = np.array([np.random.randint(1, 11) for i in range(7)])

print(np.dot(a, b))


241


In [27]:
"Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою."
a = np.random.randint(11, size=(2,2))
b = np.random.randint(11, size=(2,3))
result = np.dot(a, b)
print(result)


[[37 42 16]
 [64 66 28]]


In [35]:
"Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю."
matrix = np.random.randint(1, 11, size=(3, 3))
inverse_matrix = np.linalg.inv(matrix)
print(matrix)
print(inverse_matrix)

[[ 4  6  9]
 [ 4 10  7]
 [ 9  1  1]]
[[-0.00735294 -0.00735294  0.11764706]
 [-0.14460784  0.18872549 -0.01960784]
 [ 0.21078431 -0.12254902 -0.03921569]]


In [42]:
"Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її."
matrix = np.random.rand(4, 4)
transposed_matrix = np.transpose(matrix)
print("Оригінальна матриця (4x4):")
print(matrix)
print("Транспонована матриця (4x4):")
print(transposed_matrix)

Оригінальна матриця (4x4):
[[0.21701832 0.79897095 0.13215178 0.86856171]
 [0.66731211 0.57509169 0.72137473 0.68059875]
 [0.95018574 0.31392386 0.71073567 0.65327102]
 [0.9129699  0.87600303 0.88933237 0.19264938]]
Транспонована матриця (4x4):
[[0.21701832 0.66731211 0.95018574 0.9129699 ]
 [0.79897095 0.57509169 0.31392386 0.87600303]
 [0.13215178 0.72137473 0.71073567 0.88933237]
 [0.86856171 0.68059875 0.65327102 0.19264938]]


In [56]:
"Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор."
vector = np.array([np.random.randint(1, 11) for i in range(4)])
matrix = np.array(np.random.randint(1, 11, size=(3, 4)))
print("Вектор:")
print(vector)
print("Матриця:")
print(matrix)

Вектор:
[9 8 4 5]
Матриця:
[[ 6  9 10  6]
 [ 1  7  3  6]
 [ 2  7  1  3]]


In [55]:
"Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор"
vector = np.array([np.random.randint(0, 2) for i in range (3)])
matrix = np.array(np.random.randint(0, 2, size=(2, 3)))
print("Вектор:")
print(vector)
print("Матриця:")
print(matrix)
result = (matrix * vector)
print("Результат:")
print(result)   

Вектор:
[1 1 0]
Матриця:
[[0 0 0]
 [1 1 1]]
Результат:
[[0 0 0]
 [1 1 0]]


In [58]:
"Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення."
matrix_1 = np.array(np.random.randint(1, 11, size=(2, 2)))
matrix_2 = np.array(np.random.randint(1, 11, size=(2, 2)))
print("Матриця 1:")
print(matrix_1)
print("Матриця 2:")
print(matrix_2)
result = (matrix_1 * matrix_2)
print("Результат:")
print(result)

Матриця 1:
[[5 3]
 [9 9]]
Матриця 2:
[[3 3]
 [8 1]]
Результат:
[[15  9]
 [72  9]]


In [59]:
"Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток."
matrix_1 = np.array(np.random.randint(1, 11, size=(2, 2)))
matrix_2 = np.array(np.random.randint(1, 11, size=(2, 2)))
print("Матриця 1:")
print(matrix_1)
print("Матриця 2:")
print(matrix_2)
result = np.dot(matrix_1, matrix_2)
print("Результат:")
print(result)

Матриця 1:
[[8 7]
 [3 1]]
Матриця 2:
[[ 6 10]
 [ 5  4]]
Результат:
[[ 83 108]
 [ 23  34]]


In [60]:
"Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці."
matrix = np.random.randint(1, 100, size=(5, 5))
matrix_sum = np.sum(matrix)
print("Матриця:")
print(matrix)
print("Сума елементів матриці:")
print(matrix_sum)

Матриця:
[[24 22 14 66 98]
 [39  8 77 70 35]
 [73 79 17 81 30]
 [56 78 42 71 13]
 [53 12 71 83  4]]
Сума елементів матриці:
1216


In [63]:
"Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю."
matrix_1 = np.array(np.random.randint(1, 10, size=(4, 4)))
matrix_2 = np.array(np.random.randint(1, 10, size=(4, 4)))
print("Матриця 1:")
print(matrix_1)
print("Матриця 2:")
print(matrix_2)
result = (matrix_1 - matrix_2)
print("Результат:")
print(result)

Матриця 1:
[[3 2 9 4]
 [5 1 8 6]
 [6 6 7 7]
 [2 7 5 4]]
Матриця 2:
[[8 7 8 6]
 [6 1 2 8]
 [1 1 2 5]
 [6 7 8 4]]
Результат:
[[-5 -5  1 -2]
 [-1  0  6 -2]
 [ 5  5  5  2]
 [-4  0 -3  0]]


In [66]:
"Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці."
matrix = np.array(np.random.randint(0, 2, size=(3, 3)))
vector = np.array([matrix[0].sum(), matrix[1].sum(), matrix[2].sum()]).reshape(-1, 1)
print("Вектор:")
print(vector)

Вектор:
[[0]
 [1]
 [2]]


In [67]:
"Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел."
matrix = np.random.randint(0, 10, size=(3, 4))
squared_matrix = np.square(matrix)

print("Вихідна матриця:")
print(matrix)

print("Матриця з квадратами чисел:")
print(squared_matrix)

Вихідна матриця:
[[5 4 4 2]
 [1 6 4 5]
 [1 9 9 8]]
Матриця з квадратами чисел:
[[25 16 16  4]
 [ 1 36 16 25]
 [ 1 81 81 64]]


In [70]:
"Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел."
vector = np.array([np.random.randint(1, 50+1) for i in range (4)])
squared_vector = np.square(vector)
print("Вектор:")
print(vector)
print("Вектор з квадратами чисел:")
print(squared_vector)

Вектор:
[ 9 13 27 21]
Вектор з квадратами чисел:
[ 81 169 729 441]
