In [1]:
import random
import numpy as np

"Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення."
vector = np.arange(1, 11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
"Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення."
matrix = np.zeros((3, 3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
"Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення."
matrix = np.random.randint(11, size=(5, 5))
print(matrix)

[[ 3  0  2  8  1]
 [ 1  6  1  5  9]
 [ 1  9  6  4  2]
 [ 3  8  2  5 10]
 [10  1  4  2  5]]


In [4]:
"Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення."
matrix = np.random.randint(2, size=(4, 4))
print(matrix)

[[0 1 1 1]
 [1 1 0 1]
 [1 0 1 0]
 [0 1 1 0]]


In [5]:
"Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення."
a = np.array([np.random.randint(1, 11) for i in range(5)])
b = np.array([np.random.randint(1, 11) for i in range(5)])

print(a + b)
print(a - b)
print(a * b)

[ 8 11  5 17 11]
[-6 -1 -1  1 -3]
[ 7 30  6 72 28]


In [6]:
"Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток."
a = np.array([np.random.randint(1, 11) for i in range(7)])
b = np.array([np.random.randint(1, 11) for i in range(7)])

print(np.dot(a, b))


175


In [7]:
"Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою."
a = np.random.randint(11, size=(2,2))
b = np.random.randint(11, size=(2,3))
result = np.dot(a, b)
print(result)


[[  0   0   0]
 [ 29  42 122]]


In [8]:
"Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю."
matrix = np.random.randint(1, 11, size=(3, 3))
inverse_matrix = np.linalg.inv(matrix)
print(matrix)
print(inverse_matrix)

[[6 2 9]
 [3 4 4]
 [2 1 6]]
[[ 0.36363636 -0.05454545 -0.50909091]
 [-0.18181818  0.32727273  0.05454545]
 [-0.09090909 -0.03636364  0.32727273]]


In [9]:
"Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її."
matrix = np.random.rand(4, 4)
transposed_matrix = np.transpose(matrix)
print("Оригінальна матриця (4x4):")
print(matrix)
print("Транспонована матриця (4x4):")
print(transposed_matrix)

Оригінальна матриця (4x4):
[[0.15862081 0.42074148 0.66366855 0.66289677]
 [0.32130277 0.94327373 0.27115965 0.14273034]
 [0.25376785 0.25832541 0.41396406 0.48003555]
 [0.07979834 0.48844624 0.62212824 0.10331526]]
Транспонована матриця (4x4):
[[0.15862081 0.32130277 0.25376785 0.07979834]
 [0.42074148 0.94327373 0.25832541 0.48844624]
 [0.66366855 0.27115965 0.41396406 0.62212824]
 [0.66289677 0.14273034 0.48003555 0.10331526]]


In [10]:
"Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор."
vector = np.array([np.random.randint(1, 11) for i in range(4)])
matrix = np.array(np.random.randint(1, 11, size=(3, 4)))
print("Вектор:")
print(vector)
print("Матриця:")
print(matrix)

Вектор:
[3 2 8 7]
Матриця:
[[ 2  1  2  7]
 [ 3  8  8 10]
 [ 3  1  5  1]]


In [11]:
"Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор"
vector = np.array([np.random.randint(0, 2) for i in range (3)])
matrix = np.array(np.random.randint(0, 2, size=(2, 3)))
print("Вектор:")
print(vector)
print("Матриця:")
print(matrix)
result = (matrix * vector)
print("Результат:")
print(result)   

Вектор:
[1 1 0]
Матриця:
[[1 1 1]
 [1 1 1]]
Результат:
[[1 1 0]
 [1 1 0]]


In [12]:
"Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення."
matrix_1 = np.array(np.random.randint(1, 11, size=(2, 2)))
matrix_2 = np.array(np.random.randint(1, 11, size=(2, 2)))
print("Матриця 1:")
print(matrix_1)
print("Матриця 2:")
print(matrix_2)
result = (matrix_1 * matrix_2)
print("Результат:")
print(result)

Матриця 1:
[[2 2]
 [4 9]]
Матриця 2:
[[10  4]
 [ 5  7]]
Результат:
[[20  8]
 [20 63]]


In [13]:
"Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток."
matrix_1 = np.array(np.random.randint(1, 11, size=(2, 2)))
matrix_2 = np.array(np.random.randint(1, 11, size=(2, 2)))
print("Матриця 1:")
print(matrix_1)
print("Матриця 2:")
print(matrix_2)
result = np.dot(matrix_1, matrix_2)
print("Результат:")
print(result)

Матриця 1:
[[8 9]
 [9 7]]
Матриця 2:
[[2 4]
 [9 8]]
Результат:
[[ 97 104]
 [ 81  92]]


In [14]:
"Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці."
matrix = np.random.randint(1, 100, size=(5, 5))
matrix_sum = np.sum(matrix)
print("Матриця:")
print(matrix)
print("Сума елементів матриці:")
print(matrix_sum)

Матриця:
[[15 92 27 29 12]
 [87 28 88 54 70]
 [66 20 30 18 76]
 [28 89 66  4  6]
 [23 13 42 48 51]]
Сума елементів матриці:
1082


In [15]:
"Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю."
matrix_1 = np.array(np.random.randint(1, 10, size=(4, 4)))
matrix_2 = np.array(np.random.randint(1, 10, size=(4, 4)))
print("Матриця 1:")
print(matrix_1)
print("Матриця 2:")
print(matrix_2)
result = (matrix_1 - matrix_2)
print("Результат:")
print(result)

Матриця 1:
[[1 7 6 5]
 [7 9 8 9]
 [5 7 3 8]
 [6 5 2 9]]
Матриця 2:
[[1 7 8 4]
 [2 2 3 5]
 [9 7 2 7]
 [4 5 5 2]]
Результат:
[[ 0  0 -2  1]
 [ 5  7  5  4]
 [-4  0  1  1]
 [ 2  0 -3  7]]


In [16]:
"Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці."
matrix = np.array(np.random.randint(0, 2, size=(3, 3)))
vector = np.array([matrix[0].sum(), matrix[1].sum(), matrix[2].sum()]).reshape(-1, 1)
print("Вектор:")
print(vector)

Вектор:
[[2]
 [2]
 [2]]


In [17]:
"Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел."
matrix = np.random.randint(0, 10, size=(3, 4))
squared_matrix = np.square(matrix)

print("Вихідна матриця:")
print(matrix)

print("Матриця з квадратами чисел:")
print(squared_matrix)

Вихідна матриця:
[[8 8 0 5]
 [6 5 2 4]
 [4 6 2 3]]
Матриця з квадратами чисел:
[[64 64  0 25]
 [36 25  4 16]
 [16 36  4  9]]


In [18]:
"Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел."
vector = np.array([np.random.randint(1, 50+1) for i in range (4)])
squared_vector = np.square(vector)
print("Вектор:")
print(vector)
print("Вектор з квадратами чисел:")
print(squared_vector)

Вектор:
[11  9 49 17]
Вектор з квадратами чисел:
[ 121   81 2401  289]
